model_name: "unsloth/Qwen3-4B-Instruct-2507"
max_seq_length: 2048
load_in_4bit: true

method: "lora"

dataset_text_field: "messages"

lr: 2e-4

batch_size: 2
grad_accum: 8
epochs: 10
warmup_steps: 20
lr_scheduler_type: "cosine"

target_modules:
  - "q_proj"
  - "k_proj"
  - "v_proj"
  - "o_proj"

system_prompt: |
  Ты полезный ассистент и помогаешь отвечать на разные вопросы. Отвечай в 1-2 предложения.